### ISSUE TITLE
关于识别速率

### ISSUE THREAD

**Issue by ghost** [simplezhli/Tesseract-OCR-Scanner#1]
原来公司是打算买的，后来嫌太贵，现在想自己开发，这个引擎识别速度*准确率跟原来打算购买的那个天差之别，想问下博主，如何从这两方面去优化？
想着尝试使用识别工具JTessBoxEditor去优化识别识别库
不知道博主那边有没有比较好的识别库，如果识别速度可以，价格好说

**Comment by simplezhli** [comment]
我这边也没有识别库，但是经过训练的识别库识别效率还是很不错的。识别库主要根据业务去训练，没有通用的。否则识别库文件太大了。

**Comment by ghost** [comment]
嗯，公司准备自己训练，谢谢！
