### ISSUE TITLE
项目导入运行无法实现识别功能

### ISSUE THREAD

**Issue by kevinblog** [simplezhli/Tesseract-OCR-Scanner#2]
楼主，你好！我把这个项目导入到Android  Studio运行后，无法实现自动扫描和拍照识别功能，相机拍摄手机号码时会先聚焦然后图像变模糊，一直这样来回跳动。

**Comment by simplezhli** [comment]
https://github.com/simplezhli/Tesseract-OCR-Scanner/blob/master/app/src/main/java/com/zl/tesseract/scanner/camera/AutoFocusCallback.java#L23
这个类有设置自动对焦时间，你可以先尝试将对焦时间设置大一点。我这里也暂时无法复现。
