### ISSUE TITLE
关于自动识别

### ISSUE THREAD

**Issue by liurentian** [simplezhli/Tesseract-OCR-Scanner#3]
你好，因为自动识别的准确率不是太高，我想关闭自动扫描识别，只保留拍照识别功能，请问一下在哪里可以关闭？

**Comment by simplezhli** [comment]
https://github.com/simplezhli/Tesseract-OCR-Scanner/blob/master/app/src/main/java/com/zl/tesseract/scanner/ScannerActivity.java#L98 这行是判断扫描是二维码或数字，你可以修改为true，只扫描二维码

**Comment by simplezhli** [comment]
https://github.com/simplezhli/Tesseract-OCR-Scanner/blob/master/app/src/main/java/com/zl/tesseract/scanner/decode/DecodeHandler.java#L65  如果二维码与数字扫描都不要，可以删除这行的解码

**Comment by liurentian** [comment]
@simplezhli 感谢指点，我想要的效果是，只在我点击拍照按钮的时候去识别，不点击拍照的话只要一个相机预览就行

**Comment by GorgeAI** [comment]
hi 你好，请我你是用什么方式训练的，我训练产生的文件和格式不一样的，可以给一下你训练参考文章吗

谢谢

**Comment by simplezhli** [comment]
@fleetcor 你可以搜索关键字Tesseract-OCR训练。我找了一篇你可以看看http://www.cnblogs.com/cnlian/p/5765871.html

**Comment by GorgeAI** [comment]
非常谢谢 你自己也是用现成的训练库吗 还是自己训练的吗
训练起来感觉好麻烦

**Comment by simplezhli** [comment]
用的现成的，我们识别的都是机打数字。不需要特殊处理。
