### ISSUE TITLE
尝试修改正则，识别短串数字时结果有问题

### ISSUE THREAD

**Issue by chaoli2** [simplezhli/Tesseract-OCR-Scanner#5]
尝试用这个项目来识别短串数字，比如2-3位的数字“12”或者"123"，所以修改匹配的[正则代码](https://github.com/simplezhli/Tesseract-OCR-Scanner/blob/efa46e8b1689dd12074997b5856fc31e76f69396/app/src/main/java/com/zl/tesseract/scanner/utils/Tools.java#L172)，改成
```
 private static Pattern pattern = Pattern.compile("\\d{3}$*");
```
结果app的识别就很不稳定了，摄像头对着没有数字的空白区域，也总是跳出来一堆很乱的结果，比如下面这样：
![image](https://user-images.githubusercontent.com/24284449/62843605-a7ccd200-bced-11e9-9eed-f5c199340dd0.png)

保持正则同样的写法，只是增加待识别数字的长度(\\d{3}改成\\d{10})，识别的结果还是很准确
```
 private static Pattern pattern = Pattern.compile("\\d{10}$*");
```

所有现在有点迷惑，针对这种现象，请教博主有没有大致的思路，能推断出问题出在哪里吗？是项目其他部分的bug，还是算法和模型本身就有这个限制呢？

**Comment by simplezhli** [comment]
@chaoli2 确实是会这样，因为一般的识别结果就是数字及字母的随机组合体。如果只有2,3位数字确实很容易命中。但是手机号这种更加连续的数字却不容易出现。

从使用场景上来说，一般识别的内容也是需要有一定的规律及长度的，否则使用扫描的功夫其实人为就可以输入了。

**Comment by chaoli2** [comment]
@simplezhli 嗯，明白了。谢谢。
