### ISSUE TITLE
识别出来是html

### ISSUE THREAD

**Issue by 307295206** [simplezhli/Tesseract-OCR-Scanner#7]
为什么识别出来的是一段html字符串，含有div、p、span标签

**Comment by simplezhli** [comment]
我怀疑你在逗我。。。

**Comment by 307295206** [comment]
> 我怀疑你在逗我。。。

真没有，老铁。我是用的拍照识别，结果出来的就是一段html

**Comment by 307295206** [comment]
> 我怀疑你在逗我。。。

你联系方式给我留意下，我明天把日志打印出来让你看看
