### ISSUE TITLE
识别纯数字用哪个训练数据最好

### ISSUE THREAD

**Issue by yuanze18** [simplezhli/Tesseract-OCR-Scanner#8]

**Comment by yuanze18** [comment]
private static Pattern pattern = Pattern.compile("\\d{7,10}$*");
正则只要小于8位即使不扫描数字，扫描结果也能出来一堆奇怪的数字，这个需要改什么地方吗

**Comment by simplezhli** [comment]
@yuanze18 这没办法，要识别准确就要自己训练数据。
